version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: redpencil/frontend-redpencil.io:0.2.1
    links:
      - identifier:backend
    environment:
      GZIP: 'true'
      STATIC_FOLDERS_REGEX: '^\/(assets|fonts)\/.*'
    volumes:
      - ./data/vacancies:/app/assets/vacancies
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.6.1
    restart: always
    logging: *default-logging
